### ISSUE TITLE
pdf to icdar txt label

### ISSUE THREAD

**Issue by ghost** [MaliParag/ICDAR2019#1]
@MaliParag hi,
is there a way to convert pdf files to icdar txt labels, perhaps at line or character level?

**Comment by MaliParag** [comment]
@deepseek we provide OCR code for each character with their bounding box. 

Each row in character gt file [(for example)](https://github.com/MaliParag/TFD-ICDAR2019/blob/master/TFD-ICDAR2019v2/Train/char_gt/AIF_1970_493_498.char) is organized as follows:
Page number, left of bounding box of a character, top of the bounding box of a character, right of the bounding box of a character, bottom of the bounding box of a character, type of character (Text or Math), OCR code   

For example:
0,1088,950,1131,1000,ORDINARY_TEXT,0141

You might be able to write a script to use this information to convert the provided ground truths to the icdar txt labels.
